import { createContext } from 'react';

const AppContext = createContext({
  activeForm: '',
  activeRuntime: undefined,
  activeThemes: '',
  formClient: {},
  isSpinnerVisible: false,
  notificationProps: { message: '', type: '' },
  refreshLocalList: 0,
  refreshRemoteList: 0,
  refreshCheckpointList: 0,
  selectedDesignerConfig: '',
  spinnerMessage: '',
  isFormDesignChanged: false,
  currentLocale: '',
  hideSpinner: () => {},
  isUnsaved: () => {},
  setActiveForm: () => {},
  setActiveRuntime: () => {},
  setActiveThemes: () => {},
  setUnsavedChangesFlag: () => {},
  setChangesFlagForActiveForm: () => {},
  setIsUnsaved: () => {},
  setFormClient: () => {},
  setRefreshLocalList: () => {},
  setRefreshRemoteList: () => {},
  setRefreshCheckpointList: () => {},
  setSelectedDesignerConfig: () => {},
  showNotification: () => {},
  showSpinner: () => {},
  setIsFormDesignChanged: () => {},
  setCurrentLocale: () => {},
});

export default AppContext;
